name: nerf-rignerf-${dataset.scene}
tag: ''
seed: 42

dataset:
  name: rignerf
  scene: kuoyuan_home_glass
  root_dir: ../datasets/kuoyuan_home_glass
  img_downscale: true # specify training image size by either img_wh or img_downscale
  section: p2,p3
  up_est_method: ground # if true, use estimated ground plane normal direction as up direction
  center_est_method: lookat
  n_test_traj_steps: 27
  near_scene: 25
  far_scene: 40
  test_pose_range_start: 50 
  test_pose_range_end: 300

model:
  name: rignerf
  radius: 1.0
  num_samples_per_ray: 2048
  train_num_rays: 128
  max_train_num_rays: 8192
  grid_prune: false
  dynamic_ray_sampling: true
  batch_image_sampling: false
  randomized: true
  ray_chunk: 16384
  learned_background: true
  background_color: white
  face_focus_after: 8000 # after how many iterations, focus on facial regions (sample more rays near face)
  bias_factor: 8 # how much to bias towards face regions
  deformation:
    name: rignerf-deformation
    factor: 0.7 # when distance is D (radius of mesh), what the denominator should be
    radius: ${model.radius}
    method: nearest # trilinear
    point_encoding_config:
      otype: VanillaFrequency
      n_frequencies: 8  
    deformation_encoding_config:
      otype: VanillaFrequency
      n_frequencies: 2    
      n_masking_step: 10000
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: none
      n_neurons: 128
      n_hidden_layers: 8
  geometry:
    name: volume-density
    radius: ${model.radius}
    feature_dim: 16
    density_activation: trunc_exp
    density_bias: -1
    isosurface:
      method: mc
      resolution: 256
      chunk: 2097152
      threshold: 5.0
    xyz_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378  
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 1
  texture:
    name: rignerf-volume-radiance
    input_feature_dim: ${model.geometry.feature_dim}
    fea_3dmm_dim: 56
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4    
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: Sigmoid
      n_neurons: 64
      n_hidden_layers: 2
  
system:
  name: rignerf-system
  loss:
    lambda_rgb: 1.
    lambda_distortion: 0
  optimizer:
    name: Adam
    args:
      lr: 0.01
      betas: [0.9, 0.99]
      eps: 1.e-15
  scheduler:
    name: MultiStepLR
    interval: step
    args:
      milestones: [10000, 15000, 18000]
      gamma: 0.5

checkpoint:
  save_top_k: -1
  every_n_train_steps: 10000

export:
  chunk_size: 2097152
  export_vertex_color: False  

trainer:
  max_steps: 20000
  log_every_n_steps: 200
  num_sanity_val_steps: 0
  val_check_interval: 20000
  limit_train_batches: 1.0
  limit_val_batches: 2
  enable_progress_bar: true 
  precision: 16
